apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
  labels:
    app: nginx

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: tushargayakwad29/nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx 
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 9376  # Exposed port for the cluster 
      targetPort: 80  # Container port
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      #nodePort: 30007
  #type: NodePort