apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  namespace: httpd
  labels:
    app: httpd

spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd-container
        image: tushargayakwad29/httpd:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
  namespace: nginx
spec:
  selector:
    app: httpd
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 80
  
  
